# Generated by Django 3.2.13 on 2022-08-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0002_egitimler_kapak_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kur_Adi', models.CharField(max_length=100)),
                ('kur_tarihi', models.DateTimeField()),
            ],
        ),
    ]
