# Generated by Django 3.2.13 on 2022-08-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0003_kurlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurlar',
            name='kur_tarihi',
        ),
    ]
