# Generated by Django 3.2.13 on 2022-08-16 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0004_remove_kurlar_kur_tarihi'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurlar_secimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egitim_tarihi', models.DateTimeField()),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitimler.egitimler')),
                ('kur_Adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egitimler.kurlar')),
            ],
        ),
    ]
