# Generated by Django 3.2.13 on 2022-08-19 11:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0005_kurlar_secimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='hakkimizda_sayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hakkimizda_aciklama', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='urun_aciklama',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='urun_mufredat',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='urun_sag_metin',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='urun_sertifikalar',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='egitimler',
            name='urun_tarih_ucret',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
