# Generated by Django 3.2.13 on 2022-08-19 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egitimler', '0006_auto_20220819_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='iletisim_kanali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_kanalimiz', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
