# Generated by Django 3.2.13 on 2022-08-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sayfa_logosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sayfa_logo', models.FileField(blank=True, null=True, upload_to='logo/', verbose_name='Sayfaya Logo Ekleyin')),
            ],
        ),
    ]
