# Generated by Django 3.2.13 on 2022-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='numara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_numarasi', models.CharField(max_length=11)),
            ],
        ),
    ]
