# Generated by Django 3.2.13 on 2022-08-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_adres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sirket_email_adresi', models.EmailField(max_length=200)),
            ],
        ),
    ]
