# Generated by Django 3.2.13 on 2022-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0004_email_adres'),
    ]

    operations = [
        migrations.CreateModel(
            name='sosyalmedyafb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyaInsgr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyalinkd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='sosyalmedyaTw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=400)),
            ],
        ),
    ]
