# Generated by Django 3.2.13 on 2022-08-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_sosyalmedyafb_sosyalmedyainsgr_sosyalmedyalinkd_sosyalmedyatw'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baner_resim', models.FileField(blank=True, upload_to='banner/', verbose_name='Sayfaya resim Ekleyiniz')),
            ],
        ),
    ]
