# Generated by Django 3.2.13 on 2022-08-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='sayfa_sirasi',
            field=models.BigIntegerField(null=True),
        ),
    ]
